name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show username length
        run: |
          echo "USERNAME='${{ secrets.DOCKER_USERNAME }}'"
